Agregar integración con postgresql
kfgodel/agnostic-sql pull request #66
Opened 2020-01-10 16:22 UTC by GastonTestay

2020-01-10 16:23 UTC, GastonTestay commented on pom.xml
> +      <version>3.0.0</version>
Hubo que poner esta versión porque no existía la otra.

2020-01-11 21:17 UTC, kfgodel commented
Separé este PR en dos. El revert de nary que ya lo apliqué a master, y dejo en este sólo la integracion con postgres

2020-01-11 21:35 UTC, kfgodel requested changes
Muy buen laburo che. Dejé en rojito lo unico que cambiaría para mergearlo y sacar version nueva.

![Grosos](https://sayingimages.com/wp-content/uploads/leonardo-dicaprio-cheers-awesome-meme.jpg)

2020-01-11 21:35 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/api/vendors/Vendor.java
> +    return ClasspathTemplatingVendor.create("postgresql", "ansi");
👍

2020-01-11 21:35 UTC, kfgodel commented on src/main/resources/postgresql/types/fk.ftl
> +<#include "bigint.ftl"/>
Este es igual que el de ansi. No sería necesario incluirlo, no?

2020-01-11 21:35 UTC, kfgodel commented on src/main/resources/postgresql/types/pk.ftl
> +<#include "bigint.ftl"/> PRIMARY KEY
Muy bueno, no sabía que PK ya hacía que no fuera nullable en postgres

2020-01-11 21:35 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/AsqlShowcaseTest.java
> +        });
🛑 acá se chispoteó un doble test no?

2020-01-11 21:35 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/vendors/SelectSequenceValueTest.java
> + * Esta clase verifica que en los diferentes vendors, el select una secuencia se traduzca correctamente
![Groso!](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMVoLd2wG0rGCNZcMR7ssaRx1kf6UzW8l5RUcYRrkm0UrWRsTs&s)

2020-01-13 12:19 UTC, kfgodel approved these changes

2020-01-13 12:19 UTC, merged