Added more support for postgresql
kfgodel/agnostic-sql pull request #69
Opened 2020-01-30 18:08 UTC by GastonTestay

Fixes:
* Alter column Nullability
* Column type

Added:
* Alter column for type integer 
* Limit statement in select

2020-02-04 22:34 UTC, kfgodel requested changes
Hay varias cosas para cambiar que las marque con rojito.
Lo de la excepción es lo más importante.

Si pudieran partir este PR en 2 por cada cambio por separado, sería muy feliz pero no es obligatorio

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/vendors/ColumnAdditionTest.java
> +        context().statement(() -> asql.alter("tabla").adding(asql.column("columna").typed(DataType.booleanic()).defaultedTo(BooleanReference.create(false)).nonNullable()));
🛑 El objeto reference no debería ser conocido por el usuario del dsl.
Es un detalle interno que debemos nosotros dentro del DSL. Si no aumentamos la complejidad del uso

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/vendors/ChangeColumnNullabilityTest.java
> +          context().expectedTranslation(() -> "ALTER TABLE tabla ALTER COLUMN columna SET NOT NULL");
👍

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
Si en vez de agregar más codigo a este test que ya está grandecito, mudamos a un test nuevo?
De esa manera queda más manejable cada cosa y podemos concentrarnos en lo especificamente nuevo que es el limit

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +          assertThat(translated).isEqualTo("SELECT TOP 1 column1 FROM table1");
Estoy casi seguro que ansi no tiene TOP. Y sí tiene LIMIT. Lo chequearon esto?

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +        it("in ansi", () -> {
Falta indicar cual es el resultado esperado. "En ansi.... " qué?
"En ansi usa top", sería para matchear con la aserción

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/model/ChangeColumnModelTest.java
> +      it("can be translated to a vendor specific statement", () -> {
Este caso no tiene mucho sentido en este test. La descripción debería ser "...para postres" o algo que indique qué tiene distinto del caso anterior. Por otro lado podría estar en otro test donde se muestre la dif para cada vendor

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/model/ChangeColumnModelTest.java
> +        assertThat(translatedSql).isEqualTo("ALTER TABLE tableName ALTER COLUMN columnName TYPE INTEGER USING (columnName::integer)");
🛑 Estoy casi seguro que ese `(columnName::integer)` debería ser `integer` o `bigint`

2020-02-04 22:34 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/AsqlShowcaseTest.java
> +        it("for postgresql", () -> {
🛑 Este caso debería estar comprendido en el caso anterior (que prueba todos juntos).
O mejor aún que sea un caso para cada vendor, pero agregandoló así como está no se entiende porque es un caso aparte del resto

2020-02-04 22:34 UTC, kfgodel commented on src/main/resources/postgresql/select/select.ftl
> +    ${" "} limit ${model.limit}
Ojo con los espacios que tienen efecto. No deberíamos dejar espacios en blanco

2020-02-04 22:34 UTC, kfgodel commented on src/main/resources/postgresql/alter/change_column_type.ftl
> +      USING (<@renderAsModel model=model.columnDeclaration.column />::integer)
🛑 definitivamente el `::integer` no va acá

2020-02-04 22:34 UTC, kfgodel commented on src/main/resources/ansi/select/select.ftl
> +    <#list model.projections as projection><@renderAsModel model=projection/><#sep>, </#sep></#list>
🛑 No queremos poner el espacio implicitamente en esta linea. 
Debería estar explicitamente en la de arriba: `${" "}TOP ${model.limit}${" "}`
Eso hace que si no hay top. no se agregan espacios de más

2020-02-04 22:34 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/model/select/SelectModel.java
> +  }
Normalmente el limit se usa también con el offset. No hace falta agregarlo, pero lo comento para que lo tengan en cuenta como posible segundo elemento a agregar

2020-02-04 22:34 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/model/references/BooleanReference.java
> +//    return SymbolModel.create("/references/_" + value + ".ftl");
🛑 Esta linea no debería estar comentada, y por otro lado el model debe crearse sólo al llamar parse.
La reference no debería anticipar el estado de lo que le van a pedir. 
De esa manera se separa bien qué es lo que el usuario indicó o pasó (el booleano) y qué es lo que usamos nosotros para representar eso (el Boolean model).

Por otro lado estoy pensando si es necesario que sea un model custom. Con el SymbolModel no alcanzaba?
Fijensé que tiene practicamente el mismo comportamiento que el boolean, como lo definieron, tiene el mismo comportamiento que el symbol

2020-02-04 22:34 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/lang/select/TableDefinedSelectImpl.java
> +import ar.com.kfgodel.asql.api.AgnosticStatement;
Esto no tendría sentido. Porque agregar un import que no se usa?

2020-02-04 22:34 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/lang/select/LimitStatement.java
> +    throw new RuntimeException();
🛑 Definitivamente no 
1) Si tiran una excepcion que no sea la RuntimeException. Que sea una especifica del dominnio (en este caso existe la agnostic)
2) Al tirar una excepción quieren poner una descripción de cual es el problema, como mínimo. **Nunca una excepción vacía**

2020-02-04 22:34 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/api/select/SelectStatement.java
> +    return LimitStatement.create(this, limit);
👍

2020-02-05 14:03 UTC, GastonTestay commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
Siendo que es parte del "Select" pensamos que debería haber estado ahí.

2020-02-11 21:24 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
Claro, pero una clausula de select puede tener muchas muchas cosas que sean parte. Entonces a la hora de mantener un test que sea manejable por ahi conviene partir en partes con cierta coherencia para que no sean demasiado tests juntos en un sólo lugar

2020-02-11 23:04 UTC, kfgodel approved these changes

2020-02-11 23:04 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/lang/select/LimitStatement.java
> +    throw new AsqlException("No se pueden poner dos limit en una misma consulta.");
La excepcion debería estar en inglés. Ahí lo modifico directo en el branch

2020-02-11 23:04 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/lang/select/ProjectionDefinedSelectImpl.java
> +import ar.com.kfgodel.asql.api.AgnosticStatement;
Quito este import redundandte

2020-02-11 23:04 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/lang/select/RestrictedSelectImpl.java
> +import ar.com.kfgodel.asql.api.AgnosticStatement;
Mismo acá

2020-02-11 23:04 UTC, kfgodel commented on src/main/java/ar/com/kfgodel/asql/impl/model/references/BooleanModel.java
> +public class BooleanModel implements AgnosticModel {
Como les comentaba anteriormente, esta clase no es necesaria porque SymbolModel ya cumple esta misma función.
La quito directamente del branch

2020-02-11 23:04 UTC, kfgodel commented on src/main/resources/ansi/select/select.ftl
> +    ${" "} FETCH FIRST ${model.limit} ROWS ONLY ${" "}
Saco el espacio implicito del principio de la linea

2020-02-11 23:04 UTC, kfgodel commented on src/main/resources/postgresql/alter/change_column_type.ftl
> +</#if>
Acá le quité los espacios redundantes al template

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/AsqlShowcaseTest.java
> +        ChangeColumnStatement statement = asql.alter("tableName").changing(asql.column("columnName").typed(DataType.integer()));
Ya que esto se usa de ejemplo, cambio la manera en que se define la variable del tests para usar lo que ofrece java-spec para definir variables de test y que permite redefinir en sub-contextos. Así no se mezclan estilos distintos de definir variables.

O sea uso `context().statement()`

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/AsqlShowcaseTest.java
> +        ChangeColumnStatement statement = asql.alter("tableName").changing(asql.column("columnName").typed(DataType.integer()));
Ajusto un poco las descri´pciones de los casos para describir en qué difieren

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/AsqlShowcaseTest.java
> +        ChangeColumnStatement statement = asql.alter("tableName").changing(asql.column("columnName").typed(DataType.integer()));
Agrego la variable vendor para que se más claro que varía en cada caso,  y no repetir código

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
Lo muevo a un test aparte y le cambio las descripciones para que se formen oraciones en cada caso de test. Fijensé que son practicamente 120 lineas de codigo para tests nuevos. Es mucho para agreagar a un conjunto de tests ya existente (son muchos casos)

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
Modifico también la manera en que declaran variables y definen contextos. 
Cuando puedan charlemos respecto de este punto así les explico porqué es mejor

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
Además muevos estos casos de test al conjunto de tests para vendors. Donde basicamente se hace esta permutaciónm de vendors y se verifica el resultado

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
Además agrego los casos de los vendors faltantes

2020-02-11 23:04 UTC, kfgodel commented on src/test/java/ar/com/kfgodel/asql/statements/SelectStatementTest.java
> +    });
🛑 corrijo también el caso de hslqdb que estaba usando fetch first en vez de limit (como hace postgres)

2020-02-11 23:04 UTC, kfgodel commented on src/main/resources/postgresql/select/select.ftl
> +    ${" "} limit ${model.limit}
Modifico el keyword `limit` por `LIMIT` en mayúsculas, así es más facil a la vista discriminar nombres de cosas vs sintaxis del motor

2020-02-11 23:06 UTC, kfgodel commented
Agregué un commit con todos los cambios que mencioné. Mergeo y releseo versión

2020-02-11 23:06 UTC, merged